import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const read = (relativePath) =>
  readFileSync(new URL(`../${relativePath}`, import.meta.url), "utf8");

test("DOCX preview HTML is sanitized at every injection source", () => {
  const sanitizer = read("src/lib/sanitizeDocumentHtml.ts");
  const fileViewer = read("src/pages/FileViewer.tsx");
  const embeddedChat = read("src/components/EmbeddedChat.tsx");

  assert.match(sanitizer, /DOMPurify\.sanitize/);
  assert.match(sanitizer, /"script"/);
  assert.match(sanitizer, /"iframe"/);
  assert.match(sanitizer, /"data-docx-alt-chunk-id"/);
  assert.match(sanitizer, /"contenteditable"/);
  assert.match(sanitizer, /FORBID_ATTR: options\.allowDocxLayoutStyles \? \["srcset"\] : \["style", "srcset"\]/);
  assert.match(sanitizer, /Only enable for HTML generated by Manor's OOXML renderer/);
  assert.match(sanitizer, /sections = rendered\.sections\.map\(\(section\) => sanitizeSection\(section, options\)\)/);
  assert.match(sanitizer, /headerHtml: sanitizeDocumentHtml\(section\.headerHtml, options\)/);
  assert.match(fileViewer, /sanitizeManorDocumentRender\(rendered, sanitizeOptions\)/);
  assert.doesNotMatch(fileViewer, /import\("mammoth"\)/);
  assert.match(fileViewer, /setLegacyHtml\(sanitizeDocumentHtml\(new TextDecoder\(\)\.decode\(buf\)\)\)/);
  assert.match(embeddedChat, /sanitizeManorDocumentRender\(rendered, sanitizeOptions\)/);
  assert.match(embeddedChat, /setDocxRender\(render\)/);
  assert.doesNotMatch(embeddedChat, /import\("mammoth"\)/);
});
