"""Workspace operation draft runtime.

This service is the single staging/apply layer for changes that affect how a
workspace runs: services, rules, knowledge policy, tool/skill/integration
scope, budget, heartbeat, strategist settings, and task waves.
"""
from __future__ import annotations

import copy
import json
from datetime import date, datetime, timezone
from typing import Any

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from packages.core.ai.runtime.capability_bindings import (
    normalize_runtime_capability_binding,
    runtime_capability_binding_identity,
    validate_runtime_capability_binding,
)
from packages.core.models.base import generate_ulid
from packages.core.models.task import Conversation, Task
from packages.core.models.workspace import (
    Agent,
    AgentSubscription,
    Workspace,
    WorkspaceOperationDraft,
    WorkspaceWorkBatch,
)


class OperationConflictError(ValueError):
    """The workspace changed after the draft was created."""


class OperationValidationError(ValueError):
    """The draft cannot be safely applied."""

    def __init__(self, validation: dict[str, Any]):
        super().__init__("workspace operation draft has validation errors")
        self.validation = validation


_OPERATION_APPROVE_ACTIONS = {
    "approve",
    "approved",
    "yes",
    "accept",
    "confirm",
    "confirmed",
    "apply",
    "applied",
    "ok",
}
_OPERATION_REJECT_ACTIONS = {
    "reject",
    "rejected",
    "no",
    "deny",
    "decline",
    "cancel",
    "cancelled",
    "canceled",
    "stop",
    "stopped",
    "discard",
    "discarded",
}


def _json_safe(value: Any) -> Any:
    return json.loads(json.dumps(value, ensure_ascii=False, default=str))


def _copy_json(value: Any) -> Any:
    return copy.deepcopy(value)


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


def _as_dict(value: Any) -> dict[str, Any]:
    return dict(value) if isinstance(value, dict) else {}


def _as_list(value: Any) -> list[Any]:
    return list(value) if isinstance(value, list) else []


def _normalise_operation_review_action(action: Any) -> str | None:
    text = str(action or "").strip().lower().replace("-", "_")
    if text in _OPERATION_APPROVE_ACTIONS:
        return "approve"
    if text in _OPERATION_REJECT_ACTIONS:
        return "reject"
    return None


def _normalise_operation_review_draft_id(hitl_id: Any) -> str:
    text = str(hitl_id or "").strip()
    if text.startswith("workspace_operation:"):
        return text.split(":", 1)[1].strip()
    if text.startswith("op:"):
        return text.split(":", 1)[1].strip()
    return text


def _changed_key_summary(diff: dict[str, Any] | None) -> str:
    keys = _unique_list((diff or {}).get("changed_keys"))
    return ", ".join(keys) if keys else "workspace runtime"


def _parse_goal_deadline(value: Any) -> date | None:
    if value is None or value == "":
        return None
    if isinstance(value, datetime):
        return value.date()
    if isinstance(value, date):
        return value
    text = str(value).strip()
    if not text:
        return None
    try:
        return datetime.fromisoformat(text.replace("Z", "+00:00")).date()
    except ValueError:
        return None


def _coerce_goal_priority(value: Any, default: int = 3) -> int:
    try:
        priority = int(value)
    except (TypeError, ValueError):
        return default
    return max(1, min(5, priority))


def _workspace_subscription_prompt(
    workspace: Workspace,
    service_key: str,
    mapping: dict[str, Any],
) -> str:
    parts = [
        f'You are subscribed to the "{workspace.name}" workspace as the "{service_key}" service handler.'
        if service_key else f'You are subscribed to the "{workspace.name}" workspace.',
    ]
    if workspace.primary_work:
        parts.append(f"Workspace primary work: {workspace.primary_work}")
    if workspace.operating_context:
        parts.append(f"Operating context: {workspace.operating_context}")
    rationale = str(mapping.get("rationale") or mapping.get("reason") or "").strip()
    if rationale:
        parts.append(f"Why you were assigned: {rationale}")
    return "\n\n".join(parts)


def _is_auto_framing_prompt(value: Any) -> bool:
    """Heuristic: does this custom_prompt look auto-generated by us?

    Auto framings always start with ``You are subscribed to the "<workspace>"``.
    Operator-written prompts won't begin with that exact phrasing, so we use
    this signature to decide whether it's safe to regenerate when the
    workspace's name / context / primary_work drifts.
    """
    if not isinstance(value, str):
        return False
    return value.lstrip().startswith('You are subscribed to the "')


async def refresh_workspace_subscription_framings(
    db: AsyncSession,
    workspace: Workspace,
) -> int:
    """Regenerate auto-generated AgentSubscription framings for a workspace.

    Call this after the workspace's name, primary_work, or operating_context
    changes so subscriptions don't keep referring to stale identity. Hand-
    written custom prompts (anything that doesn't match the auto-framing
    signature) are left untouched.

    Returns the number of subscriptions that were rewritten.
    """
    rows = list((await db.execute(
        select(AgentSubscription).where(
            AgentSubscription.entity_id == workspace.entity_id,
            AgentSubscription.workspace_id == workspace.id,
            AgentSubscription.status == "active",
        )
    )).scalars().all())
    rewritten = 0
    for sub in rows:
        if not _is_auto_framing_prompt(sub.custom_prompt):
            continue
        new_prompt = _workspace_subscription_prompt(
            workspace,
            str(sub.service_key or "").strip(),
            {},
        )
        if new_prompt != sub.custom_prompt:
            sub.custom_prompt = new_prompt
            rewritten += 1
    if rewritten:
        await db.flush()
    return rewritten


def _unique_list(values: Any) -> list[str]:
    if isinstance(values, str):
        values = [values]
    if not isinstance(values, list):
        return []
    out: list[str] = []
    seen: set[str] = set()
    for value in values:
        text = str(value or "").strip()
        if text and text not in seen:
            seen.add(text)
            out.append(text)
    return out


async def _load_workspace(
    db: AsyncSession,
    workspace_id: str,
    entity_id: str,
    *,
    for_update: bool = False,
) -> Workspace | None:
    query = select(Workspace).where(
        Workspace.id == workspace_id,
        Workspace.entity_id == entity_id,
        Workspace.deleted_at.is_(None),
    )
    if for_update:
        query = query.with_for_update()
    return (await db.execute(query)).scalar_one_or_none()


async def _snapshot_workspace_state(
    db: AsyncSession,
    workspace: Workspace,
) -> dict[str, Any]:
    from packages.core.budget import get_budget_status
    from packages.core.governance import get_policy, policy_to_dict
    from packages.core.services.workspace_service import get_workspace_agent_mappings

    operating_model = _as_dict(workspace.operating_model)
    budget = await get_budget_status(db, workspace.id)
    governance_policy = policy_to_dict(await get_policy(db, workspace.id))
    agent_mappings = await get_workspace_agent_mappings(
        db,
        workspace.id,
        workspace.entity_id,
    )
    knowledge_policy = _as_dict(
        operating_model.get("knowledge_policy")
        or operating_model.get("knowledge")
    )
    state = {
        "workspace_id": workspace.id,
        "entity_id": workspace.entity_id,
        "operation_revision": int(workspace.operation_revision or 0),
        "operating_model": operating_model,
        "services": _as_list(operating_model.get("services")),
        "goals": _as_list(operating_model.get("goals")),
        "rules": _as_list(operating_model.get("rules")),
        "automations": _as_list(operating_model.get("automations")),
        "evaluation": _as_dict(operating_model.get("evaluation")),
        "knowledge_policy": knowledge_policy,
        "capability_bindings": _as_list(operating_model.get("capability_bindings")),
        "skill_bindings": _as_list(operating_model.get("skill_bindings")),
        "integration_scope": _as_dict(operating_model.get("integration_scope")),
        "channel_config": _as_dict(operating_model.get("channel_config")),
        "processes": _as_list(operating_model.get("processes")),
        "strategist": _as_dict(operating_model.get("strategist")),
        "agent_mappings": agent_mappings,
        "governance_policy": governance_policy,
        "budget_policy": {
            "monthly_budget_credits": budget.monthly_budget_credits if budget else None,
            "monthly_budget_usd": budget.monthly_budget_usd if budget else None,
            "auto_pause_on_budget": budget.auto_pause_on_budget if budget else bool(workspace.auto_pause_on_budget),
            "reset_alert_state": True,
        },
        "heartbeat_policy": {
            "enabled": bool(workspace.heartbeat_enabled),
            "cadence": workspace.heartbeat_cadence or "daily",
        },
        "immediate_tasks": [],
    }
    return _sync_operating_model_from_state(state)


def _sync_operating_model_from_state(state: dict[str, Any]) -> dict[str, Any]:
    om = _as_dict(state.get("operating_model"))
    for key in (
        "services",
        "goals",
        "rules",
        "automations",
        "evaluation",
        "capability_bindings",
        "skill_bindings",
        "integration_scope",
        "channel_config",
        "processes",
        "strategist",
        "agent_mappings",
    ):
        if key in state:
            om[key] = _copy_json(state[key])
    if "knowledge_policy" in state:
        om["knowledge"] = _copy_json(state.get("knowledge_policy") or {})
    if "governance_policy" in state:
        om["governance"] = _copy_json(state.get("governance_policy") or {})
    state["operating_model"] = om
    return state


def _merge_by_key(items: Any, item: dict[str, Any], *keys: str) -> list[dict[str, Any]]:
    rows = [dict(row) for row in _as_list(items) if isinstance(row, dict)]
    key_name = next((key for key in keys if item.get(key)), keys[0])
    key_value = str(item.get(key_name) or "").strip()
    if not key_value:
        rows.append(item)
        return rows
    out: list[dict[str, Any]] = []
    replaced = False
    for row in rows:
        if str(row.get(key_name) or "").strip() == key_value:
            merged = dict(row)
            merged.update(item)
            out.append(merged)
            replaced = True
        else:
            out.append(row)
    if not replaced:
        out.append(item)
    return out


def _remove_by_key(items: Any, key_name: str, key_value: str) -> list[dict[str, Any]]:
    return [
        dict(row)
        for row in _as_list(items)
        if isinstance(row, dict) and str(row.get(key_name) or "") != str(key_value)
    ]


_GOAL_IDENTITY_KEYS = ("id", "goal_id", "goal_key", "metric_key", "key", "title", "goal")


def _normalise_identity(value: Any) -> str:
    return str(value or "").strip().lower()


def _goal_identity_tokens(row: dict[str, Any]) -> set[str]:
    return {
        token
        for token in (_normalise_identity(row.get(key)) for key in _GOAL_IDENTITY_KEYS)
        if token
    }


def _goal_measurement_updates(payload: dict[str, Any]) -> list[dict[str, Any]]:
    raw_updates = (
        payload.get("updates")
        or payload.get("measurement_sources")
        or payload.get("sources")
        or payload.get("goals")
    )
    updates: list[dict[str, Any]] = []
    if isinstance(raw_updates, list):
        return [dict(row) for row in raw_updates if isinstance(row, dict)]
    if isinstance(raw_updates, dict):
        for key, raw in raw_updates.items():
            if isinstance(raw, dict):
                update = dict(raw)
            else:
                update = {"measurement_source": raw}
            update.setdefault("goal_key", key)
            updates.append(update)
        return updates
    if any(key in payload for key in (*_GOAL_IDENTITY_KEYS, "measurement_source", "source", "source_type")):
        return [dict(payload)]
    return []


def _measurement_source_from_update(update: dict[str, Any]) -> dict[str, Any] | None:
    source = _as_dict(update.get("measurement_source") or update.get("source"))
    source_type = str(
        update.get("source_type")
        or source.get("provider")
        or update.get("provider")
        or ""
    ).strip().lower()
    metric_key = str(update.get("metric_key") or "").strip()

    if not source:
        if "twitter_x" in source_type or source_type in {"x", "twitter", "twitterx"}:
            action = str(update.get("action") or "").strip() or (
                "get_me" if metric_key == "follower_count" else "get_tweet_metrics"
            )
            source = {
                "provider": "twitter_x",
                "action": action,
                "params": {"read_only": True},
            }
        elif source_type in {"manual", "manual_entry"} or source_type.startswith("manual"):
            source = {
                "provider": "manual",
                "params": {
                    "mode": "manual_entry",
                    "preserve_workspace_manual": True,
                },
            }

    if not source:
        return None

    provider = str(source.get("provider") or "").strip().lower()
    if provider in {"twitter_x_read_only", "x_read_only"}:
        source["provider"] = "twitter_x"
        source.setdefault("action", "get_me" if metric_key == "follower_count" else "get_tweet_metrics")
        params = _as_dict(source.get("params"))
        params["read_only"] = True
        source["params"] = params
    elif provider == "manual" or provider.startswith("manual_"):
        source["provider"] = "manual"
        params = _as_dict(source.get("params"))
        params.setdefault("mode", "manual_entry")
        params["preserve_workspace_manual"] = True
        source["params"] = params

    return source


def _apply_goal_measurement_updates(
    goals: Any,
    payload: dict[str, Any],
) -> list[dict[str, Any]]:
    rows = [dict(row) for row in _as_list(goals) if isinstance(row, dict)]
    for update in _goal_measurement_updates(payload):
        match_tokens = _goal_identity_tokens(update)
        if not match_tokens:
            continue

        fields: dict[str, Any] = {}
        measurement_source = _measurement_source_from_update(update)
        if measurement_source is not None:
            fields["measurement_source"] = measurement_source

        cadence = (
            update.get("measurement_cadence")
            or update.get("cadence")
            or update.get("refresh_cadence")
        )
        if cadence is not None:
            fields["measurement_cadence"] = str(cadence or "").strip() or None

        if update.get("baseline_value") is not None or update.get("baseline") is not None:
            fields["baseline_value"] = update.get("baseline_value", update.get("baseline"))
        if update.get("current_value") is not None or update.get("current") is not None:
            fields["current_value"] = update.get("current_value", update.get("current"))

        for key in ("metric_key", "target_value", "target", "status", "deadline", "description", "priority"):
            if key in update and update[key] is not None:
                fields["target_value" if key == "target" else key] = update[key]

        if not fields:
            continue

        matched = False
        for idx, goal in enumerate(rows):
            if _goal_identity_tokens(goal) & match_tokens:
                merged = dict(goal)
                merged.update(fields)
                rows[idx] = merged
                matched = True

        if not matched and str(update.get("title") or update.get("goal") or "").strip():
            goal = {
                "goal_key": update.get("goal_key") or update.get("key") or update.get("metric_key"),
                "title": update.get("title") or update.get("goal"),
                "metric_key": update.get("metric_key") or update.get("goal_key") or update.get("key"),
                "target_value": update.get("target_value") or update.get("target") or 1,
                **fields,
            }
            rows.append({key: value for key, value in goal.items() if value is not None})
    return rows


def _normalise_patch(raw_patch: dict[str, Any]) -> tuple[str, dict[str, Any]]:
    if not isinstance(raw_patch, dict):
        raise ValueError("operation patch must be an object")
    op = str(
        raw_patch.get("op")
        or raw_patch.get("operation")
        or raw_patch.get("type")
        or ""
    ).strip()
    if not op:
        raise ValueError("operation patch requires op")
    payload = raw_patch.get("payload")
    if payload is None:
        payload = {
            key: value
            for key, value in raw_patch.items()
            if key not in {"op", "operation", "type"}
        }
    return op, _as_dict(payload)


def _apply_single_patch(
    state: dict[str, Any],
    raw_patch: dict[str, Any],
) -> dict[str, Any]:
    from packages.core.services.workspace_setup_service import _enrich_operating_rules

    op, payload = _normalise_patch(raw_patch)

    if op in {"operating_model.replace", "workspace_model.replace"}:
        om = _as_dict(payload.get("operating_model") or payload)
        state["operating_model"] = om
        state["services"] = _as_list(om.get("services"))
        state["goals"] = _as_list(om.get("goals"))
        state["rules"] = _enrich_operating_rules(om.get("rules") or [])
        state["automations"] = _as_list(om.get("automations"))
        state["evaluation"] = _as_dict(om.get("evaluation"))
        state["knowledge_policy"] = _as_dict(om.get("knowledge") or om.get("knowledge_policy"))
        state["capability_bindings"] = _as_list(om.get("capability_bindings"))
        state["skill_bindings"] = _as_list(om.get("skill_bindings"))
        state["integration_scope"] = _as_dict(om.get("integration_scope"))
        state["channel_config"] = _as_dict(om.get("channel_config"))
        state["processes"] = _as_list(om.get("processes"))
        state["strategist"] = _as_dict(om.get("strategist"))
        state["agent_mappings"] = _as_list(om.get("agent_mappings"))
        return _sync_operating_model_from_state(state)

    if op in {"operating_model.update", "workspace_model.update"}:
        om_update = _as_dict(payload.get("operating_model") or payload)
        om = _as_dict(state.get("operating_model"))
        om.update(_copy_json(om_update))
        state["operating_model"] = om
        for key in (
            "services",
            "goals",
            "rules",
            "automations",
            "evaluation",
            "capability_bindings",
            "skill_bindings",
            "integration_scope",
            "channel_config",
            "processes",
            "strategist",
            "agent_mappings",
        ):
            if key in om_update:
                state[key] = _as_dict(om.get(key)) if key in {
                    "evaluation",
                    "integration_scope",
                    "channel_config",
                    "strategist",
                } else _as_list(om.get(key))
        if "knowledge" in om_update or "knowledge_policy" in om_update:
            state["knowledge_policy"] = _as_dict(om.get("knowledge") or om.get("knowledge_policy"))
        if "governance" in om_update or "governance_policy" in om_update:
            state["governance_policy"] = _as_dict(om.get("governance") or om.get("governance_policy"))
        return _sync_operating_model_from_state(state)

    if op in {"evaluation.update", "scorecard.update"}:
        evaluation = _as_dict(state.get("evaluation"))
        evaluation.update(_as_dict(payload.get("evaluation") or payload))
        state["evaluation"] = evaluation
        return _sync_operating_model_from_state(state)

    if op in {"budget_policy.update", "budget.update"}:
        budget = _as_dict(state.get("budget_policy"))
        budget.update(payload)
        # Budget snapshots expose both the persisted USD value and a derived
        # credit value. If a later patch updates only one representation, the
        # stale counterpart must not keep winning during apply.
        if "monthly_budget_usd" in payload and "monthly_budget_credits" not in payload:
            if payload.get("monthly_budget_usd") is None:
                budget["monthly_budget_credits"] = 0
            else:
                budget.pop("monthly_budget_credits", None)
        if "monthly_budget_credits" in payload and "monthly_budget_usd" not in payload:
            if payload.get("monthly_budget_credits") is None:
                budget["monthly_budget_credits"] = 0
            budget.pop("monthly_budget_usd", None)
        state["budget_policy"] = budget
        return _sync_operating_model_from_state(state)

    if op in {"heartbeat_policy.update", "heartbeat.update"}:
        heartbeat = _as_dict(state.get("heartbeat_policy"))
        heartbeat.update(payload)
        state["heartbeat_policy"] = heartbeat
        return _sync_operating_model_from_state(state)

    if op in {"governance_policy.update", "governance.update"}:
        governance = _as_dict(state.get("governance_policy"))
        governance.update(
            _as_dict(payload.get("governance_policy") or payload.get("governance") or payload)
        )
        state["governance_policy"] = governance
        return _sync_operating_model_from_state(state)

    if op in {"rule.add", "guardrail.add"}:
        rule = _as_dict(payload.get("rule") or payload)
        rules = _as_list(state.get("rules"))
        enriched = _enrich_operating_rules(rules + [rule])
        state["rules"] = _dedupe_rule_dicts(enriched)
        return _sync_operating_model_from_state(state)

    if op in {"rules.replace", "guardrails.replace"}:
        state["rules"] = _enrich_operating_rules(payload.get("rules") or [])
        return _sync_operating_model_from_state(state)

    if op in {"goals.replace", "goal.replace"}:
        state["goals"] = _as_list(payload.get("goals") or [])
        return _sync_operating_model_from_state(state)

    if op in {"goal.upsert", "goal.add"}:
        goal = _as_dict(payload.get("goal") or payload)
        key = "goal_key" if goal.get("goal_key") else "key"
        state["goals"] = _merge_by_key(state.get("goals"), goal, key)
        return _sync_operating_model_from_state(state)

    if op in {
        "goal.measurement_source.update",
        "goal.measurement_sources.update",
        "goals.measurement_sources.update",
        "measurement_sources.update",
        "goal_sources.update",
    }:
        state["goals"] = _apply_goal_measurement_updates(state.get("goals"), payload)
        return _sync_operating_model_from_state(state)

    if op in {"service_role.upsert", "service.upsert"}:
        service = _as_dict(payload.get("service") or payload)
        if service.get("service_key") and not service.get("key"):
            service["key"] = service["service_key"]
        state["services"] = _merge_by_key(state.get("services"), service, "key", "service_key")
        return _sync_operating_model_from_state(state)

    if op in {"service_role.remove", "service.remove"}:
        key = str(payload.get("key") or payload.get("service_key") or "").strip()
        if key:
            state["services"] = _remove_by_key(state.get("services"), "key", key)
            state["agent_mappings"] = [
                dict(row)
                for row in _as_list(state.get("agent_mappings"))
                if isinstance(row, dict) and str(row.get("service_key") or "").strip() != key
            ]
        return _sync_operating_model_from_state(state)

    if op in {"knowledge_policy.update", "knowledge.update"}:
        policy = _as_dict(state.get("knowledge_policy"))
        policy.update(payload)
        state["knowledge_policy"] = policy
        return _sync_operating_model_from_state(state)

    if op in {"capability_binding.upsert", "tool_scope.update"}:
        bindings = payload.get("bindings")
        if isinstance(bindings, list):
            for binding in bindings:
                if isinstance(binding, dict):
                    state["capability_bindings"] = _upsert_capability_binding(
                        state.get("capability_bindings"),
                        binding,
                    )
        else:
            binding = _as_dict(payload.get("binding") or payload)
            state["capability_bindings"] = _upsert_capability_binding(
                state.get("capability_bindings"),
                binding,
            )
        return _sync_operating_model_from_state(state)

    if op in {"capability_binding.remove", "tool_scope.remove"}:
        binding_key = str(payload.get("binding_key") or payload.get("key") or "").strip()
        if binding_key:
            state["capability_bindings"] = _remove_by_key(
                state.get("capability_bindings"),
                "binding_key",
                binding_key,
            )
        return _sync_operating_model_from_state(state)

    if op in {"skill_binding.upsert", "skill_scope.update"}:
        binding = _as_dict(payload.get("binding") or payload)
        state["skill_bindings"] = _upsert_capability_binding(
            state.get("skill_bindings"),
            binding,
            default_type="skill",
        )
        return _sync_operating_model_from_state(state)

    if op in {"integration_scope.update", "integration.update"}:
        scope = _as_dict(state.get("integration_scope"))
        scope.update(payload)
        state["integration_scope"] = scope
        return _sync_operating_model_from_state(state)

    if op in {"channel.upsert", "channel_config.upsert"}:
        channel = _as_dict(payload.get("channel") or payload)
        channel_config = _as_dict(state.get("channel_config"))
        channels = _merge_by_key(
            channel_config.get("channels"),
            channel,
            "channel_id",
            "channel_type",
        )
        channel_config["channels"] = channels
        state["channel_config"] = channel_config
        return _sync_operating_model_from_state(state)

    if op in {"agent_binding.upsert", "agent_mapping.upsert"}:
        mapping = _as_dict(payload.get("mapping") or payload)
        state["agent_mappings"] = _merge_by_key(
            state.get("agent_mappings"),
            mapping,
            "service_key",
            "agent_subscription_id",
            "agent_id",
        )
        return _sync_operating_model_from_state(state)

    if op in {"agent_binding.remove", "agent_mapping.remove"}:
        key = str(payload.get("service_key") or payload.get("key") or "").strip()
        if key:
            state["agent_mappings"] = [
                dict(row)
                for row in _as_list(state.get("agent_mappings"))
                if isinstance(row, dict) and str(row.get("service_key") or "").strip() != key
            ]
        return _sync_operating_model_from_state(state)

    if op in {"agent_mappings.replace", "agent_mapping.replace"}:
        state["agent_mappings"] = _as_list(
            payload.get("agent_mappings")
            or payload.get("mappings")
            or payload.get("agent_bindings")
            or []
        )
        return _sync_operating_model_from_state(state)

    if op in {"process.upsert", "workflow.upsert"}:
        process = _as_dict(payload.get("process") or payload)
        key = "process_key" if process.get("process_key") else "key"
        state["processes"] = _merge_by_key(state.get("processes"), process, key)
        return _sync_operating_model_from_state(state)

    if op in {"strategist.update", "strategist_policy.update"}:
        strategist = _as_dict(state.get("strategist"))
        strategist.update(payload)
        state["strategist"] = strategist
        return _sync_operating_model_from_state(state)

    if op in {"task.prepare", "immediate_task.add"}:
        task = _as_dict(payload.get("task") or payload)
        state["immediate_tasks"] = _as_list(state.get("immediate_tasks")) + [task]
        return _sync_operating_model_from_state(state)

    raise ValueError(f"unsupported workspace operation patch: {op}")


def _dedupe_rule_dicts(rules: list[Any]) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    seen: set[str] = set()
    for idx, raw_rule in enumerate(rules):
        if not isinstance(raw_rule, dict):
            continue
        rule = dict(raw_rule)
        explicit_key = str(rule.get("rule_key") or "").strip()
        description = str(rule.get("description") or "").strip()
        dedupe = explicit_key or description
        if dedupe and dedupe in seen:
            continue
        if dedupe:
            seen.add(dedupe)
        rule["rule_key"] = explicit_key or f"rule_{idx + 1}"
        out.append(rule)
    return out


def _binding_identity(binding: dict[str, Any]) -> str:
    return runtime_capability_binding_identity(binding)


def _upsert_capability_binding(
    items: Any,
    raw_binding: dict[str, Any],
    *,
    default_type: str = "tool",
) -> list[dict[str, Any]]:
    binding = normalize_runtime_capability_binding(raw_binding, default_type=default_type)
    rows = [dict(row) for row in _as_list(items) if isinstance(row, dict)]
    return _merge_by_key(rows, binding, "binding_key")


def _state_diff(base: dict[str, Any], target: dict[str, Any]) -> dict[str, Any]:
    keys = (
        "services",
        "goals",
        "rules",
        "evaluation",
        "knowledge_policy",
        "capability_bindings",
        "skill_bindings",
        "integration_scope",
        "channel_config",
        "processes",
        "strategist",
        "agent_mappings",
        "governance_policy",
        "budget_policy",
        "heartbeat_policy",
        "immediate_tasks",
    )
    changed: dict[str, Any] = {}
    for key in keys:
        before = base.get(key)
        after = target.get(key)
        if before != after:
            changed[key] = {"before": _json_safe(before), "after": _json_safe(after)}
    return {
        "changed_keys": list(changed.keys()),
        "changes": changed,
    }


async def get_current_operation_state(
    db: AsyncSession,
    workspace_id: str,
    entity_id: str,
) -> dict[str, Any] | None:
    workspace = await _load_workspace(db, workspace_id, entity_id)
    if workspace is None:
        return None
    return await _snapshot_workspace_state(db, workspace)


async def create_operation_draft(
    db: AsyncSession,
    workspace_id: str,
    entity_id: str,
    *,
    user_id: str | None = None,
    source_event_id: str | None = None,
    initial_patches: list[dict[str, Any]] | None = None,
) -> WorkspaceOperationDraft | None:
    workspace = await _load_workspace(db, workspace_id, entity_id)
    if workspace is None:
        return None
    state = await _snapshot_workspace_state(db, workspace)
    patches: list[dict[str, Any]] = []
    for patch in initial_patches or []:
        state = _apply_single_patch(state, patch)
        patches.append(_json_safe(patch))
    draft = WorkspaceOperationDraft(
        id=generate_ulid(),
        workspace_id=workspace.id,
        entity_id=workspace.entity_id,
        created_by_user_id=user_id,
        source_event_id=source_event_id,
        base_revision=int(workspace.operation_revision or 0),
        status="open",
        current_state=_json_safe(state),
        patches=patches,
    )
    db.add(draft)
    await db.flush()
    draft.validation = await validate_operation_draft(db, draft)
    draft.diff = await preview_operation_diff(db, draft)
    await db.flush()
    return draft


async def get_operation_draft(
    db: AsyncSession,
    draft_id: str,
    entity_id: str,
    workspace_id: str | None = None,
) -> WorkspaceOperationDraft | None:
    filters = [
        WorkspaceOperationDraft.id == draft_id,
        WorkspaceOperationDraft.entity_id == entity_id,
    ]
    if workspace_id:
        filters.append(WorkspaceOperationDraft.workspace_id == workspace_id)
    return (await db.execute(select(WorkspaceOperationDraft).where(*filters))).scalar_one_or_none()


async def patch_operation_draft(
    db: AsyncSession,
    draft_id: str,
    entity_id: str,
    workspace_id: str,
    patches: list[dict[str, Any]],
) -> WorkspaceOperationDraft | None:
    draft = await get_operation_draft(db, draft_id, entity_id, workspace_id)
    if draft is None:
        return None
    if draft.status != "open":
        raise OperationConflictError(f"cannot patch {draft.status} operation draft")
    state = _copy_json(draft.current_state or {})
    appended = _as_list(draft.patches)
    for patch in patches:
        state = _apply_single_patch(state, patch)
        appended.append(_json_safe(patch))
    draft.current_state = _json_safe(state)
    draft.patches = appended
    draft.validation = await validate_operation_draft(db, draft)
    draft.diff = await preview_operation_diff(db, draft)
    await db.flush()
    return draft


async def validate_operation_draft(
    db: AsyncSession,
    draft: WorkspaceOperationDraft,
    *,
    current_state: dict[str, Any] | None = None,
) -> dict[str, Any]:
    state = _as_dict(draft.current_state)
    errors: list[dict[str, Any]] = []
    warnings: list[dict[str, Any]] = []
    missing_setup: list[str] = []

    services = [row for row in _as_list(state.get("services")) if isinstance(row, dict)]
    service_keys = {
        str(row.get("key") or row.get("service_key") or "").strip()
        for row in services
        if str(row.get("key") or row.get("service_key") or "").strip()
    }

    for idx, service in enumerate(services):
        key = str(service.get("key") or service.get("service_key") or "").strip()
        if not key:
            errors.append({"path": f"services[{idx}].key", "message": "service requires key/service_key"})

    for idx, mapping in enumerate(_as_list(state.get("agent_mappings"))):
        if not isinstance(mapping, dict):
            continue
        service_key = str(mapping.get("service_key") or "").strip()
        if service_key and service_keys and service_key not in service_keys:
            errors.append({
                "path": f"agent_mappings[{idx}].service_key",
                "message": f"agent mapping references unknown service {service_key!r}",
            })

    agent_ids_by_idx: dict[int, str] = {}
    for idx, mapping in enumerate(_as_list(state.get("agent_mappings"))):
        if not isinstance(mapping, dict):
            continue
        agent_id = str(
            mapping.get("agent_id")
            or mapping.get("recommended_agent_id")
            or ""
        ).strip()
        if agent_id:
            agent_ids_by_idx[idx] = agent_id
    if agent_ids_by_idx:
        rows = list((await db.execute(
            select(Agent).where(
                Agent.id.in_(set(agent_ids_by_idx.values())),
                Agent.deleted_at.is_(None),
                Agent.status == "active",
            )
        )).scalars().all())
        agents_by_id = {agent.id: agent for agent in rows}
        for idx, agent_id in agent_ids_by_idx.items():
            agent = agents_by_id.get(agent_id)
            if agent is None:
                errors.append({
                    "path": f"agent_mappings[{idx}].agent_id",
                    "message": f"agent {agent_id!r} was not found",
                })
                continue
            if agent.entity_id and agent.entity_id != draft.entity_id and not agent.is_template:
                errors.append({
                    "path": f"agent_mappings[{idx}].agent_id",
                    "message": "agent belongs to another entity",
                })

    _validate_capability_bindings(
        state.get("capability_bindings"),
        service_keys,
        errors,
        prefix="capability_bindings",
    )
    _validate_capability_bindings(
        state.get("skill_bindings"),
        service_keys,
        errors,
        prefix="skill_bindings",
    )

    budget = _as_dict(state.get("budget_policy"))
    for key in ("monthly_budget_credits", "monthly_budget_usd"):
        value = budget.get(key)
        if value is not None:
            try:
                if float(value) < 0:
                    errors.append({"path": f"budget_policy.{key}", "message": f"{key} cannot be negative"})
            except (TypeError, ValueError):
                errors.append({"path": f"budget_policy.{key}", "message": f"{key} must be numeric"})

    heartbeat = _as_dict(state.get("heartbeat_policy"))
    cadence = str(heartbeat.get("cadence") or "").strip()
    if heartbeat.get("enabled") and not cadence:
        errors.append({"path": "heartbeat_policy.cadence", "message": "enabled heartbeat requires cadence"})
    if cadence and cadence not in {"hourly", "daily", "weekly", "biweekly"} and " " not in cadence:
        errors.append({
            "path": "heartbeat_policy.cadence",
            "message": "cadence must be hourly/daily/weekly/biweekly or a cron expression",
        })

    rules = [row for row in _as_list(state.get("rules")) if isinstance(row, dict)]
    for idx, rule in enumerate(rules):
        if not rule.get("description") and not rule.get("rule_key"):
            warnings.append({"path": f"rules[{idx}]", "message": "rule has no description"})
        if (
            rule.get("runtime_enforced")
            and not rule.get("action_patterns")
            and not rule.get("capability_patterns")
        ):
            warnings.append({
                "path": f"rules[{idx}].capability_patterns",
                "message": "runtime rule has no action or capability patterns",
            })

    for idx, task in enumerate(_as_list(state.get("immediate_tasks"))):
        if not isinstance(task, dict):
            errors.append({"path": f"immediate_tasks[{idx}]", "message": "task draft must be an object"})
            continue
        if not str(task.get("title") or "").strip():
            errors.append({"path": f"immediate_tasks[{idx}].title", "message": "task draft requires title"})

    if not services:
        missing_setup.append("services")
    if not rules:
        warnings.append({"path": "rules", "message": "workspace has no persistent runtime rules"})

    current = (
        current_state
        if current_state is not None
        else await get_current_operation_state(db, draft.workspace_id, draft.entity_id)
    )
    budget_impact = _budget_impact(current or {}, state)

    validation = {
        "valid": not errors,
        "errors": errors,
        "warnings": warnings,
        "missing_setup": missing_setup,
        "budget_impact": budget_impact,
        "checked_at": _utcnow().isoformat(),
    }
    draft.validation = _json_safe(validation)
    return draft.validation


def _validate_capability_bindings(
    bindings: Any,
    service_keys: set[str],
    errors: list[dict[str, Any]],
    *,
    prefix: str,
) -> None:
    for idx, raw_binding in enumerate(_as_list(bindings)):
        if not isinstance(raw_binding, dict):
            errors.append({"path": f"{prefix}[{idx}]", "message": "binding must be an object"})
            continue
        if raw_binding.get("enabled") is False:
            continue
        binding_errors = validate_runtime_capability_binding(
            raw_binding,
            path=f"{prefix}[{idx}]",
            service_keys=service_keys,
        )
        errors.extend(binding_errors)


def _budget_impact(base: dict[str, Any], target: dict[str, Any]) -> dict[str, Any]:
    before = _as_dict(base.get("budget_policy"))
    after = _as_dict(target.get("budget_policy"))
    return {
        "before": {
            "monthly_budget_credits": before.get("monthly_budget_credits"),
            "monthly_budget_usd": before.get("monthly_budget_usd"),
            "auto_pause_on_budget": before.get("auto_pause_on_budget"),
        },
        "after": {
            "monthly_budget_credits": after.get("monthly_budget_credits"),
            "monthly_budget_usd": after.get("monthly_budget_usd"),
            "auto_pause_on_budget": after.get("auto_pause_on_budget"),
        },
        "changed": before != after,
    }


async def preview_operation_diff(
    db: AsyncSession,
    draft: WorkspaceOperationDraft,
    *,
    current_state: dict[str, Any] | None = None,
) -> dict[str, Any]:
    current = (
        current_state
        if current_state is not None
        else await get_current_operation_state(db, draft.workspace_id, draft.entity_id)
    )
    diff = _state_diff(current or {}, _as_dict(draft.current_state))
    draft.diff = _json_safe(diff)
    return draft.diff


async def _sync_goals_from_operation_state(
    db: AsyncSession,
    workspace: Workspace,
    raw_goals: Any,
    *,
    deactivate_missing: bool,
) -> dict[str, int]:
    """Materialize operation goals into the runtime Goal table.

    ``operating_model.goals`` is the editable contract, but Strategist and
    measurement jobs read Goal rows. Keep those two layers aligned when a user
    applies an operation draft.
    """
    from packages.core.goals.scheduling import (
        install_measurement_schedule,
        remove_measurement_schedule,
        should_install_measurement_schedule,
    )
    from packages.core.goals.service import create_goal, update_goal
    from packages.core.models.goal import Goal
    from packages.core.services.workspace_setup_service import _coerce_goal_number

    existing_goals = list((await db.execute(
        select(Goal).where(
            Goal.entity_id == workspace.entity_id,
            Goal.workspace_id == workspace.id,
        )
    )).scalars().all())
    by_metric = {g.metric_key: g for g in existing_goals if g.metric_key}

    created = 0
    updated = 0
    paused = 0
    scheduled = 0
    desired_metric_keys: set[str] = set()

    def _merged_measurement_source(existing_source: Any, incoming_source: Any) -> dict | None:
        if not isinstance(incoming_source, dict) or not incoming_source:
            return None
        if not isinstance(existing_source, dict) or not existing_source:
            return incoming_source

        same_provider = existing_source.get("provider") == incoming_source.get("provider")
        same_action = existing_source.get("action") == incoming_source.get("action")
        if same_provider and same_action:
            # Drafts often carry the concise public contract
            # ({provider, action}) while runtime rows contain private routing
            # hints such as params/_sandbox. Preserve those hints unless the
            # draft explicitly replaces them.
            return {**existing_source, **incoming_source}
        return incoming_source

    for raw in _as_list(raw_goals):
        if not isinstance(raw, dict):
            continue
        metric_key = str(
            raw.get("metric_key")
            or raw.get("goal_key")
            or raw.get("key")
            or raw.get("title")
            or raw.get("goal")
            or "untitled_goal"
        ).strip()
        if not metric_key:
            continue
        desired_metric_keys.add(metric_key)

        existing = by_metric.get(metric_key)
        title = str(
            raw.get("title")
            or raw.get("goal")
            or (existing.title if existing else None)
            or raw.get("goal_key")
            or raw.get("key")
            or "Untitled Goal"
        ).strip() or "Untitled Goal"
        target_raw = raw.get("target_value") if raw.get("target_value") is not None else raw.get("target")
        target_value = (
            _coerce_goal_number(target_raw)
            if target_raw is not None or existing is None
            else existing.target_value
        )
        baseline_value = (
            _coerce_goal_number(raw["baseline_value"])
            if raw.get("baseline_value") is not None
            else (existing.baseline_value if existing else None)
        )
        current_value = (
            _coerce_goal_number(raw["current_value"])
            if raw.get("current_value") is not None
            else (existing.current_value if existing else None)
        )
        if "measurement_source" in raw:
            measurement_source = _merged_measurement_source(
                existing.measurement_source if existing else None,
                raw.get("measurement_source"),
            )
        else:
            measurement_source = existing.measurement_source if existing else None
        if "measurement_cadence" in raw or "cadence" in raw:
            measurement_cadence = str(
                raw.get("measurement_cadence")
                or raw.get("cadence")
                or ""
            ).strip() or None
        else:
            measurement_cadence = existing.measurement_cadence if existing else None
        status = str(raw.get("status") or (existing.status if existing else "active")).strip().lower()
        if status not in {"active", "achieved", "abandoned", "paused"}:
            status = "active"
        deadline = (
            _parse_goal_deadline(raw.get("deadline"))
            if "deadline" in raw
            else (existing.deadline if existing else None)
        )
        description = raw.get("description") if "description" in raw else (existing.description if existing else None)
        priority = _coerce_goal_priority(raw.get("priority")) if "priority" in raw else (
            existing.priority if existing else _coerce_goal_priority(None)
        )

        if existing:
            goal = await update_goal(
                db,
                existing.id,
                workspace.entity_id,
                title=title,
                description=description,
                metric_key=metric_key,
                target_value=target_value,
                baseline_value=baseline_value,
                current_value=current_value,
                deadline=deadline,
                measurement_source=measurement_source,
                measurement_cadence=measurement_cadence,
                priority=priority,
                status=status,
            )
            updated += 1 if goal else 0
        else:
            goal = await create_goal(
                db,
                entity_id=workspace.entity_id,
                workspace_id=workspace.id,
                title=title,
                description=description,
                metric_key=metric_key,
                target_value=target_value,
                baseline_value=baseline_value,
                deadline=deadline,
                measurement_source=measurement_source,
                measurement_cadence=measurement_cadence,
                priority=priority,
                install_schedule=False,
            )
            if status != "active":
                goal.status = status
            if current_value is not None:
                goal.current_value = current_value
            created += 1

        if not goal:
            continue
        if goal.status == "active" and should_install_measurement_schedule(goal):
            await install_measurement_schedule(db, goal)
            scheduled += 1
        else:
            await remove_measurement_schedule(db, goal)

    if deactivate_missing:
        for goal in existing_goals:
            if goal.metric_key in desired_metric_keys or goal.status != "active":
                continue
            goal.status = "paused"
            await remove_measurement_schedule(db, goal)
            paused += 1

    await db.flush()
    return {
        "created": created,
        "updated": updated,
        "paused": paused,
        "scheduled": scheduled,
    }


async def _sync_agent_mappings_from_operation_state(
    db: AsyncSession,
    workspace: Workspace,
    raw_mappings: Any,
    *,
    deactivate_missing: bool,
) -> dict[str, int]:
    """Materialize service->agent mappings into AgentSubscription rows."""
    from packages.core.services.workspace_service import map_agent_to_service
    from packages.core.services.workspace_setup_service import _provision_custom_agent_for_mapping

    existing_subs = list((await db.execute(
        select(AgentSubscription).where(
            AgentSubscription.entity_id == workspace.entity_id,
            AgentSubscription.workspace_id == workspace.id,
            AgentSubscription.status == "active",
        )
    )).scalars().all())
    existing_by_service = {
        str(sub.service_key or "").strip(): sub
        for sub in existing_subs
        if str(sub.service_key or "").strip()
    }

    created = 0
    updated = 0
    unchanged = 0
    deactivated = 0
    custom_agents = 0
    reused_existing_agents = 0
    skipped = 0
    desired_service_keys: set[str] = set()
    custom_agent_cache: dict[str, tuple[str, str]] = {}

    existing_auto_agents = list((await db.execute(
        select(Agent).where(
            Agent.entity_id == workspace.entity_id,
            Agent.source == "auto_workspace_setup",
            Agent.status == "active",
            Agent.deleted_at.is_(None),
        )
    )).scalars().all())
    existing_auto_agent_by_name: dict[str, Agent] = {}
    for agent in existing_auto_agents:
        name_key = str(agent.name or "").strip().lower()
        if name_key and name_key not in existing_auto_agent_by_name:
            existing_auto_agent_by_name[name_key] = agent

    for raw in _as_list(raw_mappings):
        if not isinstance(raw, dict):
            continue
        mapping = dict(raw)
        service_key = str(mapping.get("service_key") or "").strip()
        if not service_key:
            skipped += 1
            continue
        desired_service_keys.add(service_key)

        agent_id = str(
            mapping.get("agent_id")
            or mapping.get("recommended_agent_id")
            or ""
        ).strip()
        if not agent_id and mapping.get("strategy") == "create_custom":
            create_draft = _as_dict(mapping.get("create_agent_draft"))
            agent_name = str(
                create_draft.get("agent_name")
                or mapping.get("agent_name")
                or mapping.get("recommended_agent_name")
                or service_key.replace("_", " ").title()
            ).strip()
            cache_key = agent_name.lower()
            if cache_key in custom_agent_cache:
                agent_id, _agent_name = custom_agent_cache[cache_key]
            elif cache_key in existing_auto_agent_by_name:
                # An earlier apply (or finalize_setup) already auto-provisioned
                # an agent with this exact name for this entity. Reuse it
                # instead of creating duplicates that pile up across applies.
                existing_agent = existing_auto_agent_by_name[cache_key]
                agent_id = existing_agent.id
                custom_agent_cache[cache_key] = (agent_id, existing_agent.name)
                reused_existing_agents += 1
            else:
                agent_id, _agent_name = await _provision_custom_agent_for_mapping(
                    db,
                    entity_id=workspace.entity_id,
                    workspace_id=workspace.id,
                    workspace_name=workspace.name,
                    operating_context=workspace.operating_context or "",
                    primary_work=workspace.primary_work or "",
                    mapping=mapping,
                )
                custom_agent_cache[cache_key] = (agent_id, _agent_name)
                custom_agents += 1
        if not agent_id:
            skipped += 1
            continue

        existing = existing_by_service.get(service_key)
        before_agent_id = existing.agent_id if existing else None
        before_custom_prompt = existing.custom_prompt if existing else None
        requested_prompt = mapping.get("custom_prompt")
        if requested_prompt is not None:
            custom_prompt = str(requested_prompt)
        elif existing and existing.custom_prompt and not _is_auto_framing_prompt(existing.custom_prompt):
            # Operator wrote this prompt by hand — leave it alone.
            custom_prompt = existing.custom_prompt
        else:
            # No existing prompt, or the existing one is our own auto framing
            # (which may now reference a stale workspace name / context /
            # primary work). Regenerate from current workspace metadata.
            custom_prompt = _workspace_subscription_prompt(workspace, service_key, mapping)
        sub = await map_agent_to_service(
            db,
            workspace.id,
            workspace.entity_id,
            service_key,
            agent_id,
            custom_prompt=custom_prompt,
        )
        if existing is None:
            created += 1
        elif before_agent_id != agent_id or before_custom_prompt != custom_prompt:
            updated += 1
        else:
            unchanged += 1
        existing_by_service[service_key] = sub

    if deactivate_missing:
        for sub in existing_subs:
            service_key = str(sub.service_key or "").strip()
            if service_key and service_key not in desired_service_keys:
                sub.status = "inactive"
                deactivated += 1

    await db.flush()
    return {
        "created": created,
        "updated": updated,
        "unchanged": unchanged,
        "deactivated": deactivated,
        "custom_agents": custom_agents,
        "reused_existing_agents": reused_existing_agents,
        "skipped": skipped,
    }


def _operation_channel_blocks(channel_config: Any) -> list[tuple[str, dict[str, Any]]]:
    config = _as_dict(channel_config)
    out: list[tuple[str, dict[str, Any]]] = []
    for raw in _as_list(config.get("channels")):
        if isinstance(raw, dict):
            role = str(raw.get("role") or "channel").strip() or "channel"
            out.append((role, dict(raw)))
    legacy = (
        ("primary_external", config.get("primary_external_channel")),
        ("internal", config.get("internal_channel")),
    )
    for role, raw in legacy:
        if isinstance(raw, dict) and raw.get("channel_type"):
            out.append((role, dict(raw)))
    for raw in _as_list(config.get("secondary_external_channels")):
        if isinstance(raw, dict):
            out.append(("secondary_external", dict(raw)))
    return out


def _channel_config_match(
    configs: list[Any],
    *,
    channel_type: str,
    role: str,
    linked_service_key: str,
) -> Any | None:
    fallback_matches: list[Any] = []
    for config in configs:
        cfg = _as_dict(getattr(config, "config", None))
        if (
            getattr(config, "channel_type", None) == channel_type
            and str(cfg.get("role") or "") == role
            and str(cfg.get("linked_service_key") or "") == linked_service_key
        ):
            return config
        if (
            getattr(config, "channel_type", None) == channel_type
            and not str(cfg.get("role") or "").strip()
            and not str(cfg.get("linked_service_key") or "").strip()
        ):
            fallback_matches.append(config)
    if len(fallback_matches) == 1:
        return fallback_matches[0]
    return None


async def _sync_channels_from_operation_state(
    db: AsyncSession,
    workspace: Workspace,
    channel_config_state: Any,
) -> dict[str, int]:
    """Materialize operation channels into ChannelConfig + Channel rows."""
    from packages.core.models.channel import ChannelConfig
    from packages.core.models.document import Channel

    builtins = {"webchat", "internal_chat", "in_app"}
    subs = list((await db.execute(
        select(AgentSubscription).where(
            AgentSubscription.entity_id == workspace.entity_id,
            AgentSubscription.workspace_id == workspace.id,
            AgentSubscription.status == "active",
        )
    )).scalars().all())
    sub_by_service = {
        str(sub.service_key or "").strip(): sub
        for sub in subs
        if str(sub.service_key or "").strip()
    }
    first_sub = subs[0] if subs else None
    existing_configs = list((await db.execute(
        select(ChannelConfig).where(
            ChannelConfig.entity_id == workspace.entity_id,
            ChannelConfig.status == "active",
            ChannelConfig.workspace_id == workspace.id,
        )
    )).scalars().all())
    existing_channels = list((await db.execute(
        select(Channel).where(
            Channel.entity_id == workspace.entity_id,
            Channel.workspace_id == workspace.id,
        )
    )).scalars().all())

    created_configs = 0
    updated_configs = 0
    created_bindings = 0
    updated_bindings = 0
    skipped = 0
    created_config_ids: set[str] = set()

    def _binding_for_config(config_id: str) -> Any | None:
        for row in existing_channels:
            if str(_as_dict(row.config).get("channel_config_id") or "") == config_id:
                return row
        return None

    for role, block in _operation_channel_blocks(channel_config_state):
        channel_type = str(block.get("channel_type") or block.get("type") or "").strip()
        if not channel_type:
            skipped += 1
            continue
        provider = str(block.get("provider") or channel_type).strip()
        linked_service_key = str(block.get("linked_service_key") or block.get("service_key") or "").strip()
        sub = sub_by_service.get(linked_service_key) if linked_service_key else None
        if not sub:
            sub = first_sub

        config_row = None
        channel_config_id = str(block.get("channel_config_id") or "").strip()
        if channel_config_id:
            config_row = (await db.execute(
                select(ChannelConfig).where(
                    ChannelConfig.id == channel_config_id,
                    ChannelConfig.entity_id == workspace.entity_id,
                    ChannelConfig.status == "active",
                )
            )).scalar_one_or_none()
            if not config_row:
                skipped += 1
                continue
            # ChannelConfig rows are workspace-scoped. Refuse to bind an
            # inbound channel of THIS workspace to a config row that belongs
            # to a different workspace — that would silently route messages
            # across workspace boundaries.
            existing_workspace_id = getattr(config_row, "workspace_id", None)
            if existing_workspace_id and existing_workspace_id != workspace.id:
                skipped += 1
                continue
        else:
            if provider not in builtins and channel_type not in builtins:
                skipped += 1
                continue
            config_row = _channel_config_match(
                existing_configs,
                channel_type=channel_type,
                role=role,
                linked_service_key=linked_service_key,
            )
            if not config_row:
                config_row = ChannelConfig(
                    id=generate_ulid(),
                    entity_id=workspace.entity_id,
                    workspace_id=workspace.id,
                    channel_type=channel_type,
                    provider=provider,
                    credentials={},
                    status="active",
                )
                db.add(config_row)
                existing_configs.append(config_row)
                created_configs += 1
                created_config_ids.add(config_row.id)

        config_payload = _as_dict(getattr(config_row, "config", None))
        config_payload.update(_as_dict(block.get("config")))
        public_token = str(block.get("public_token") or config_payload.get("public_token") or "").strip()
        if channel_type == "webchat" and not public_token:
            public_token = generate_ulid()
        config_payload.update({
            "role": role,
            "purpose": block.get("purpose") or config_payload.get("purpose") or "",
            "linked_service_key": linked_service_key,
            "login_required": bool(block.get("login_required", config_payload.get("login_required", False))),
            "notes": block.get("notes") or config_payload.get("notes") or "",
        })
        if public_token:
            config_payload["public_token"] = public_token

        before_config = _json_safe(getattr(config_row, "config", {}) or {})
        before_name = getattr(config_row, "name", None)
        config_row.workspace_id = workspace.id
        config_row.channel_type = channel_type
        config_row.provider = provider
        config_row.name = block.get("name") or config_row.name or f"{role}: {channel_type}"
        config_row.config = _json_safe(config_payload)
        if config_row.id not in created_config_ids and (
            before_config != config_row.config or before_name != config_row.name
        ):
            updated_configs += 1

        binding_config = {
            "channel_config_id": config_row.id,
            "role": role,
            "purpose": config_payload.get("purpose") or "",
            "linked_service_key": linked_service_key,
        }
        if public_token:
            binding_config["public_token"] = public_token

        binding = _binding_for_config(config_row.id)
        if binding:
            before_binding = (
                binding.agent_id,
                binding.agent_subscription_id,
                _json_safe(binding.config or {}),
                binding.name,
                binding.status,
            )
            binding.agent_id = sub.agent_id if sub else block.get("agent_id")
            binding.agent_subscription_id = sub.id if sub else block.get("agent_subscription_id")
            binding.name = block.get("name") or binding.name or config_row.name or channel_type
            binding.type = channel_type
            binding.config = _json_safe(binding_config)
            binding.status = "active"
            after_binding = (
                binding.agent_id,
                binding.agent_subscription_id,
                _json_safe(binding.config or {}),
                binding.name,
                binding.status,
            )
            if before_binding != after_binding:
                updated_bindings += 1
        else:
            binding = Channel(
                id=generate_ulid(),
                entity_id=workspace.entity_id,
                workspace_id=workspace.id,
                type=channel_type,
                name=block.get("name") or config_row.name or channel_type,
                agent_id=sub.agent_id if sub else block.get("agent_id"),
                agent_subscription_id=sub.id if sub else block.get("agent_subscription_id"),
                config=_json_safe(binding_config),
                status="active",
            )
            db.add(binding)
            existing_channels.append(binding)
            created_bindings += 1

    await db.flush()
    return {
        "created_configs": created_configs,
        "updated_configs": updated_configs,
        "created_bindings": created_bindings,
        "updated_bindings": updated_bindings,
        "skipped": skipped,
    }


async def apply_operation_draft(
    db: AsyncSession,
    draft_id: str,
    entity_id: str,
    workspace_id: str,
    *,
    user_id: str | None = None,
    user_confirmation: bool = False,
) -> dict[str, Any] | None:
    if not user_confirmation:
        raise OperationValidationError({
            "valid": False,
            "errors": [{"path": "user_confirmation", "message": "user confirmation is required before applying"}],
            "warnings": [],
        })

    draft = await get_operation_draft(db, draft_id, entity_id, workspace_id)
    if draft is None:
        return None
    if draft.status != "open":
        raise OperationConflictError(f"cannot apply {draft.status} operation draft")

    workspace = await _load_workspace(db, workspace_id, entity_id, for_update=True)
    if workspace is None:
        return None
    if int(draft.base_revision or 0) != int(workspace.operation_revision or 0):
        raise OperationConflictError(
            "workspace operation draft is stale; create a new draft before applying"
        )

    # Snapshot the live workspace state once under the for_update lock and
    # reuse it for validation + diff so neither path re-loads workspace,
    # budget, governance, and agent mappings independently.
    current_state = await _snapshot_workspace_state(db, workspace)
    validation = await validate_operation_draft(db, draft, current_state=current_state)
    if validation.get("errors"):
        raise OperationValidationError(validation)
    applied_diff = await preview_operation_diff(db, draft, current_state=current_state)
    changed_keys = set((applied_diff or {}).get("changed_keys") or [])
    rules_touched = any(
        _normalise_patch(patch)[0] in {"rule.add", "guardrail.add", "rules.replace", "guardrails.replace"}
        for patch in _as_list(draft.patches)
        if isinstance(patch, dict)
    )

    state = _sync_operating_model_from_state(_as_dict(draft.current_state))
    operating_model = _as_dict(state.get("operating_model"))

    from packages.core.budget import set_workspace_budget
    from packages.core.governance import policy_to_dict, update_policy
    from packages.core.services.workspace_runtime import sync_workspace_runtime_schedules
    from packages.core.services.workspace_service import record_activity
    from packages.core.services.workspace_setup_service import (
        _build_governance_policy_from_rules,
        _enrich_operating_rules,
    )
    from packages.core.workspace_chat.context import invalidate

    operating_rules = _enrich_operating_rules(operating_model.get("rules") or [])
    operating_model["rules"] = operating_rules
    workspace.operating_model = _json_safe(operating_model)

    if "budget_policy" in changed_keys:
        budget = _as_dict(state.get("budget_policy"))
        await set_workspace_budget(
            db,
            workspace.id,
            monthly_budget_credits=budget.get("monthly_budget_credits"),
            monthly_budget_usd=budget.get("monthly_budget_usd"),
            auto_pause_on_budget=budget.get("auto_pause_on_budget"),
            reset_alert_state=bool(budget.get("reset_alert_state", True)),
        )

    heartbeat = _as_dict(state.get("heartbeat_policy"))
    if "enabled" in heartbeat:
        workspace.heartbeat_enabled = bool(heartbeat.get("enabled"))
    cadence = str(heartbeat.get("cadence") or "").strip()
    if cadence:
        workspace.heartbeat_cadence = cadence
    elif workspace.heartbeat_enabled and not workspace.heartbeat_cadence:
        workspace.heartbeat_cadence = "daily"
    await sync_workspace_runtime_schedules(db, workspace)

    raw_governance_policy = _as_dict(
        state.get("governance_policy") or operating_model.get("governance")
    )
    if rules_touched and "governance_policy" not in changed_keys:
        # ``rules.replace`` must remove stale action gates that were inferred
        # from previous rules. Preserve non-action policy knobs, but rebuild
        # never_allow / HITL / auto-approve lists from the current rules.
        raw_governance_policy = {
            key: value
            for key, value in raw_governance_policy.items()
            if key not in {
                "never_allow_actions",
                "hitl_required_actions",
                "auto_approve_actions",
                "never_allow_capabilities",
                "hitl_required_capabilities",
                "auto_approve_capabilities",
            }
        }
    governance_policy = _build_governance_policy_from_rules(
        operating_rules,
        raw_governance_policy,
    )
    if governance_policy is not None and (rules_touched or {"rules", "governance_policy"} & changed_keys):
        operating_model["governance"] = policy_to_dict(governance_policy)
        workspace.operating_model = _json_safe(operating_model)
        await update_policy(
            db,
            entity_id=workspace.entity_id,
            workspace_id=workspace.id,
            policy=governance_policy,
            changed_by=user_id,
            change_summary="Workspace operation draft applied",
        )

    replace_goal_set = any(
        _as_dict(patch).get("op") in {"goals.replace", "goal.replace", "operating_model.replace", "workspace_model.replace"}
        for patch in _as_list(draft.patches)
    )
    replace_agent_mapping_set = any(
        _as_dict(patch).get("op") in {
            "agent_mappings.replace",
            "agent_mapping.replace",
            "agent_mapping.remove",
            "agent_binding.remove",
            "service_role.remove",
            "service.remove",
            "operating_model.replace",
            "workspace_model.replace",
        }
        for patch in _as_list(draft.patches)
    )
    goal_result = {"created": 0, "updated": 0, "paused": 0, "scheduled": 0}
    if "goals" in changed_keys:
        goal_result = await _sync_goals_from_operation_state(
            db,
            workspace,
            state.get("goals"),
            deactivate_missing=replace_goal_set,
        )
    agent_mapping_result = {
        "created": 0,
        "updated": 0,
        "unchanged": 0,
        "deactivated": 0,
        "custom_agents": 0,
        "reused_existing_agents": 0,
        "skipped": 0,
    }
    if "agent_mappings" in changed_keys:
        agent_mapping_result = await _sync_agent_mappings_from_operation_state(
            db,
            workspace,
            state.get("agent_mappings"),
            deactivate_missing=replace_agent_mapping_set,
        )
    channel_result = {
        "created_configs": 0,
        "updated_configs": 0,
        "created_bindings": 0,
        "updated_bindings": 0,
        "skipped": 0,
    }
    if "channel_config" in changed_keys:
        channel_result = await _sync_channels_from_operation_state(
            db,
            workspace,
            state.get("channel_config"),
        )

    task_result = await _materialize_immediate_tasks(
        db,
        workspace,
        state.get("immediate_tasks"),
        draft_id=draft.id,
        user_id=user_id,
    )

    workspace.operation_revision = int(workspace.operation_revision or 0) + 1
    draft.status = "applied"
    draft.applied_at = _utcnow()
    draft.validation = validation
    draft.diff = applied_diff
    invalidate(workspace.id)

    await record_activity(
        db,
        workspace.id,
        workspace.entity_id,
        event_type="workspace_operation.applied",
        summary="Workspace operation draft applied",
        details={
            "draft_id": draft.id,
            "base_revision": draft.base_revision,
            "new_revision": workspace.operation_revision,
            "changed_keys": (draft.diff or {}).get("changed_keys") or [],
            "goals": goal_result,
            "agent_mappings": agent_mapping_result,
            "channels": channel_result,
            "tasks_created": task_result["task_ids"],
            "batch_id": task_result.get("batch_id"),
        },
        user_id=user_id,
    )
    await db.flush()
    return {
        "draft": draft_to_dict(draft),
        "workspace_revision": workspace.operation_revision,
        "tasks_created": task_result["tasks_created"],
        "goals": goal_result,
        "agent_mappings": agent_mapping_result,
        "channels": channel_result,
        "batch": task_result.get("batch"),
    }


async def repair_workspace_operation_runtime(
    db: AsyncSession,
    workspace_id: str,
    entity_id: str,
    *,
    user_id: str | None = None,
) -> dict[str, Any] | None:
    """Idempotently repair runtime rows from the persisted operating model.

    This is for older workspaces that already have operation JSON but were
    created before goals, subscriptions, and channels were materialized into
    their runtime tables. Repair is additive: it does not increment
    operation_revision and does not deactivate rows that are missing from JSON.
    """
    workspace = await _load_workspace(db, workspace_id, entity_id, for_update=True)
    if workspace is None:
        return None

    from packages.core.governance import update_policy
    from packages.core.services.workspace_runtime import sync_workspace_runtime_schedules
    from packages.core.services.workspace_service import record_activity
    from packages.core.services.workspace_setup_service import (
        _build_governance_policy_from_rules,
        _enrich_operating_rules,
    )
    from packages.core.workspace_chat.context import invalidate

    operating_model = _as_dict(workspace.operating_model)
    state = _sync_operating_model_from_state({
        "operating_model": operating_model,
        "services": _as_list(operating_model.get("services")),
        "goals": _as_list(operating_model.get("goals")),
        "rules": _as_list(operating_model.get("rules")),
        "knowledge_policy": _as_dict(operating_model.get("knowledge") or operating_model.get("knowledge_policy")),
        "capability_bindings": _as_list(operating_model.get("capability_bindings")),
        "skill_bindings": _as_list(operating_model.get("skill_bindings")),
        "integration_scope": _as_dict(operating_model.get("integration_scope")),
        "channel_config": _as_dict(operating_model.get("channel_config")),
        "processes": _as_list(operating_model.get("processes")),
        "strategist": _as_dict(operating_model.get("strategist")),
        "agent_mappings": _as_list(operating_model.get("agent_mappings")),
    })

    operating_rules = _enrich_operating_rules(state.get("rules") or [])
    operating_model["rules"] = operating_rules
    workspace.operating_model = _json_safe(operating_model)

    await sync_workspace_runtime_schedules(db, workspace)

    governance_policy = _build_governance_policy_from_rules(
        operating_rules,
        operating_model.get("governance"),
    )
    governance_result = {"updated": False}
    if governance_policy is not None and operating_rules:
        await update_policy(
            db,
            entity_id=workspace.entity_id,
            workspace_id=workspace.id,
            policy=governance_policy,
            changed_by=user_id,
            change_summary="Workspace operation runtime repair",
        )
        governance_result["updated"] = True

    goal_result = await _sync_goals_from_operation_state(
        db,
        workspace,
        state.get("goals"),
        deactivate_missing=False,
    )
    agent_mapping_result = await _sync_agent_mappings_from_operation_state(
        db,
        workspace,
        state.get("agent_mappings"),
        deactivate_missing=False,
    )
    channel_result = await _sync_channels_from_operation_state(
        db,
        workspace,
        state.get("channel_config"),
    )

    invalidate(workspace.id)
    result = {
        "workspace_id": workspace.id,
        "workspace_revision": int(workspace.operation_revision or 0),
        "goals": goal_result,
        "agent_mappings": agent_mapping_result,
        "channels": channel_result,
        "governance": governance_result,
    }
    await record_activity(
        db,
        workspace.id,
        workspace.entity_id,
        event_type="workspace_operation.runtime_repaired",
        summary="Workspace operation runtime repaired",
        details=result,
        user_id=user_id,
    )
    await db.flush()
    return result


async def _materialize_immediate_tasks(
    db: AsyncSession,
    workspace: Workspace,
    raw_tasks: Any,
    *,
    draft_id: str,
    user_id: str | None,
) -> dict[str, Any]:
    from packages.core.services import task_service

    task_payloads = [row for row in _as_list(raw_tasks) if isinstance(row, dict)]
    if not task_payloads:
        return {"tasks_created": [], "task_ids": [], "batch": None, "batch_id": None}

    tasks_created: list[Task] = []
    for payload in task_payloads:
        details = _as_dict(payload.get("details"))
        details.update({
            "workspace_operation_draft_id": draft_id,
            "runtime_context": _as_dict(payload.get("runtime_context")),
        })
        task = await task_service.create_task(
            db,
            workspace.entity_id,
            title=str(payload.get("title") or "").strip(),
            description=str(payload.get("description") or ""),
            priority=int(payload.get("priority") or 3),
            task_type=str(payload.get("task_type") or "general"),
            workspace_id=workspace.id,
            assignee_id=payload.get("assignee_id"),
            agent_id=payload.get("agent_id"),
            agent_type=payload.get("agent_type"),
            creator_id=user_id,
            details=details,
            deadline=payload.get("deadline"),
        )
        if payload.get("owner_service_key"):
            task.owner_service_key = str(payload["owner_service_key"])
        if payload.get("owner_subscription_id"):
            task.owner_subscription_id = str(payload["owner_subscription_id"])
        if isinstance(payload.get("delegate_service_keys"), list):
            task.delegate_service_keys = _unique_list(payload.get("delegate_service_keys"))
        tasks_created.append(task)

    batch = await create_work_batch(
        db,
        workspace_id=workspace.id,
        entity_id=workspace.entity_id,
        task_ids=[task.id for task in tasks_created],
        created_by_user_id=user_id,
        source_draft_id=draft_id,
        source_kind="workspace_operation",
        summary=f"Workspace operation task wave ({len(tasks_created)} tasks)",
    )
    for task in tasks_created:
        details = _as_dict(task.details)
        details["workspace_work_batch_id"] = batch.id
        task.details = details
    await db.flush()

    return {
        "tasks_created": [_task_to_dict(task) for task in tasks_created],
        "task_ids": [task.id for task in tasks_created],
        "batch": work_batch_to_dict(batch),
        "batch_id": batch.id,
    }


async def create_work_batch(
    db: AsyncSession,
    *,
    workspace_id: str,
    entity_id: str,
    task_ids: list[str],
    created_by_user_id: str | None = None,
    source_draft_id: str | None = None,
    source_kind: str | None = None,
    summary: str | None = None,
    details: dict[str, Any] | None = None,
) -> WorkspaceWorkBatch:
    batch = WorkspaceWorkBatch(
        id=generate_ulid(),
        workspace_id=workspace_id,
        entity_id=entity_id,
        created_by_user_id=created_by_user_id,
        source_draft_id=source_draft_id,
        source_kind=source_kind,
        summary=summary,
        status="active",
        task_ids=_json_safe(task_ids),
        details=_json_safe(details or {}),
    )
    db.add(batch)
    await db.flush()
    return batch


async def check_work_batch_completion(
    db: AsyncSession,
    task: Task,
    *,
    trigger_source: str = "task_status_changed",
) -> WorkspaceWorkBatch | None:
    """Complete a task wave once all tasks in it reach a terminal state.

    Strategist should react to a whole wave finishing, not to every individual
    task. This keeps workspace autonomy useful without creating review spam.
    """
    from packages.core.services.task_state_machine import TERMINAL_STATUSES
    from packages.core.services.workspace_service import record_activity

    if task.status in TERMINAL_STATUSES:
        try:
            from packages.core.services.task_dependencies import release_or_block_dependents

            await release_or_block_dependents(
                db,
                task,
                trigger_source=trigger_source,
            )
        except Exception:
            pass

    details = _as_dict(task.details)
    batch_id = str(details.get("workspace_work_batch_id") or "").strip()
    if not batch_id or not task.workspace_id:
        return None
    if task.status not in TERMINAL_STATUSES:
        return None

    batch = (await db.execute(
        select(WorkspaceWorkBatch)
        .where(
            WorkspaceWorkBatch.id == batch_id,
            WorkspaceWorkBatch.workspace_id == task.workspace_id,
            WorkspaceWorkBatch.entity_id == task.entity_id,
        )
        .with_for_update()
    )).scalar_one_or_none()
    if batch is None or batch.status != "active":
        return None

    task_ids = _unique_list(batch.task_ids)
    if not task_ids:
        batch.status = "completed"
        batch.completed_at = _utcnow()
        await db.flush()
        return batch

    rows = list((await db.execute(
        select(Task.id, Task.status)
        .where(
            Task.id.in_(task_ids),
            Task.workspace_id == task.workspace_id,
            Task.entity_id == task.entity_id,
        )
    )).all())
    statuses = {task_id: status for task_id, status in rows}
    missing = [task_id for task_id in task_ids if task_id not in statuses]
    open_ids = [
        task_id
        for task_id in task_ids
        if task_id in statuses and statuses.get(task_id) not in TERMINAL_STATUSES
    ]

    batch_details = _as_dict(batch.details)
    batch_details["progress"] = {
        "total": len(task_ids),
        "terminal": len(task_ids) - len(open_ids) - len(missing),
        "open_task_ids": open_ids,
        "missing_task_ids": missing,
        "statuses": statuses,
        "last_checked_at": _utcnow().isoformat(),
        "trigger_source": trigger_source,
    }
    batch.details = _json_safe(batch_details)

    if open_ids or missing:
        await db.flush()
        return None

    now = _utcnow()
    batch.status = "completed"
    batch.completed_at = now
    batch_details["completed_at"] = now.isoformat()
    batch.details = _json_safe(batch_details)

    try:
        await record_activity(
            db,
            task.workspace_id,
            task.entity_id,
            event_type="workspace_work_batch.completed",
            summary=f"Workspace task wave completed: {batch.summary or batch.id}",
            details={"batch_id": batch.id, "task_ids": task_ids, "trigger_source": trigger_source},
            user_id=batch.created_by_user_id,
        )
    except Exception:
        pass

    try:
        from packages.core.tasks.ai_tasks import run_strategist_review

        run_strategist_review.apply_async(
            args=[task.workspace_id, f"work_batch_completed:{batch.id}"],
            countdown=1,
        )
        batch_details["strategist_triggered_at"] = now.isoformat()
        batch.details = _json_safe(batch_details)
    except Exception:
        batch_details["strategist_trigger_error"] = "dispatch_failed"
        batch.details = _json_safe(batch_details)

    await db.flush()
    return batch


async def discard_operation_draft(
    db: AsyncSession,
    draft_id: str,
    entity_id: str,
    workspace_id: str,
    *,
    user_id: str | None = None,
) -> WorkspaceOperationDraft | None:
    filters = [
        WorkspaceOperationDraft.id == draft_id,
        WorkspaceOperationDraft.entity_id == entity_id,
        WorkspaceOperationDraft.workspace_id == workspace_id,
    ]
    draft = (await db.execute(
        select(WorkspaceOperationDraft).where(*filters).with_for_update()
    )).scalar_one_or_none()
    if draft is None:
        return None
    if draft.status == "open":
        draft.status = "discarded"
        draft.discarded_at = _utcnow()
        from packages.core.services.workspace_service import record_activity

        await record_activity(
            db,
            workspace_id,
            entity_id,
            event_type="workspace_operation.discarded",
            summary="Workspace operation draft discarded",
            details={"draft_id": draft.id},
            user_id=user_id,
        )
        await db.flush()
    return draft


async def resolve_workspace_operation_review(
    db: AsyncSession,
    *,
    conversation_id: str,
    entity_id: str,
    user_id: str,
    hitl_id: str,
    action: str,
    workspace_id: str | None = None,
) -> dict[str, Any] | None:
    """Apply or discard a workspace operation draft from a chat approval card.

    The HITL id is intentionally the draft id, so the generic chat approval
    path and workspace-chat pending_action path can share the same resolver.
    """
    draft_id = _normalise_operation_review_draft_id(hitl_id)
    normalised_action = _normalise_operation_review_action(action)
    if not draft_id or normalised_action is None:
        return None

    conv = (await db.execute(
        select(Conversation).where(
            Conversation.id == conversation_id,
            Conversation.entity_id == entity_id,
        )
    )).scalar_one_or_none()
    if conv is None:
        return None

    scoped_workspace_id = workspace_id or conv.workspace_id
    draft = await get_operation_draft(db, draft_id, entity_id, scoped_workspace_id)
    if draft is None and scoped_workspace_id is None:
        draft = await get_operation_draft(db, draft_id, entity_id)
    if draft is None:
        return None
    if scoped_workspace_id and draft.workspace_id != scoped_workspace_id:
        return None

    if normalised_action == "approve":
        if draft.status == "open":
            try:
                result = await apply_operation_draft(
                    db,
                    draft.id,
                    entity_id,
                    draft.workspace_id,
                    user_id=user_id or None,
                    user_confirmation=True,
                )
            except OperationConflictError as exc:
                return {
                    "status": "conflict",
                    "draft_id": draft.id,
                    "message": str(exc),
                    "llm_message": (
                        "[Workspace operation not applied]\n"
                        f"{exc}\n"
                        "Tell the user this draft is stale and ask whether to create a fresh operation draft."
                    ),
                }
            except OperationValidationError as exc:
                return {
                    "status": "validation_failed",
                    "draft_id": draft.id,
                    "validation": exc.validation,
                    "message": "Workspace operation validation failed.",
                    "llm_message": (
                        "[Workspace operation not applied]\n"
                        f"Validation failed: {_json_safe(exc.validation)}\n"
                        "Tell the user what must be fixed before applying."
                    ),
                }
            applied_draft = (result or {}).get("draft") or draft_to_dict(draft)
            changed = _changed_key_summary(applied_draft.get("diff") or {})
            revision = (result or {}).get("workspace_revision")
            message = f"Workspace operation approved and applied. Changed: {changed}."
            if revision is not None:
                message += f" Workspace revision is now {revision}."
            return {
                "status": "applied",
                "action": "approve",
                "draft_id": draft.id,
                "draft": applied_draft,
                "workspace_revision": revision,
                "message": message,
                "llm_message": (
                    "[Workspace operation approved]\n"
                    f"Applied draft {draft.id}. Changed: {changed}. "
                    "Do not re-apply this draft. Briefly confirm the result to the user."
                ),
            }
        changed = _changed_key_summary(_as_dict(draft.diff))
        return {
            "status": f"already_{draft.status}",
            "action": "approve",
            "draft_id": draft.id,
            "draft": draft_to_dict(draft),
            "message": f"Workspace operation draft is already {draft.status}.",
            "llm_message": (
                "[Workspace operation already resolved]\n"
                f"Draft {draft.id} is already {draft.status}. Changed: {changed}. "
                "Briefly tell the user no new apply was performed."
            ),
        }

    if draft.status == "open":
        discarded = await discard_operation_draft(
            db,
            draft.id,
            entity_id,
            draft.workspace_id,
            user_id=user_id or None,
        )
        return {
            "status": "discarded",
            "action": "reject",
            "draft_id": draft.id,
            "draft": draft_to_dict(discarded or draft),
            "message": "Workspace operation rejected and discarded.",
            "llm_message": (
                "[Workspace operation rejected]\n"
                f"Discarded draft {draft.id}. Do not apply this operation. "
                "Briefly confirm cancellation to the user."
            ),
        }
    return {
        "status": f"already_{draft.status}",
        "action": "reject",
        "draft_id": draft.id,
        "draft": draft_to_dict(draft),
        "message": f"Workspace operation draft is already {draft.status}.",
        "llm_message": (
            "[Workspace operation already resolved]\n"
            f"Draft {draft.id} is already {draft.status}. Briefly tell the user no new discard was performed."
        ),
    }


async def resolve_workspace_operation_review_message(
    db: AsyncSession,
    *,
    conversation_id: str,
    entity_id: str,
    user_id: str,
    hitl_id: str,
    action: str,
) -> str | None:
    result = await resolve_workspace_operation_review(
        db,
        conversation_id=conversation_id,
        entity_id=entity_id,
        user_id=user_id,
        hitl_id=hitl_id,
        action=action,
    )
    if not result:
        return None
    try:
        from packages.core.services.hitl_requests import mark_hitl_request_resolved
        await mark_hitl_request_resolved(
            db,
            conversation_id=conversation_id,
            hitl_id=hitl_id,
            choice=str(result.get("action") or action or ""),
        )
    except Exception:
        pass
    return str(result.get("llm_message") or result.get("message") or "").strip() or None


def _task_to_dict(task: Task) -> dict[str, Any]:
    return {
        "id": task.id,
        "workspace_id": task.workspace_id,
        "title": task.title,
        "description": task.description,
        "status": task.status,
        "priority": task.priority,
        "task_type": task.task_type,
        "owner_service_key": task.owner_service_key,
        "owner_subscription_id": task.owner_subscription_id,
        "delegate_service_keys": task.delegate_service_keys or [],
        "details": task.details or {},
    }


def draft_to_dict(draft: WorkspaceOperationDraft) -> dict[str, Any]:
    return {
        "id": draft.id,
        "workspace_id": draft.workspace_id,
        "entity_id": draft.entity_id,
        "created_by_user_id": draft.created_by_user_id,
        "source_event_id": draft.source_event_id,
        "base_revision": draft.base_revision,
        "status": draft.status,
        "current_state": _json_safe(draft.current_state or {}),
        "patches": _json_safe(draft.patches or []),
        "validation": _json_safe(draft.validation or {}),
        "diff": _json_safe(draft.diff or {}),
        "created_at": _iso_loaded(draft, "created_at"),
        "updated_at": _iso_loaded(draft, "updated_at"),
        "applied_at": _iso_loaded(draft, "applied_at"),
        "discarded_at": _iso_loaded(draft, "discarded_at"),
    }


def work_batch_to_dict(batch: WorkspaceWorkBatch) -> dict[str, Any]:
    return {
        "id": batch.id,
        "workspace_id": batch.workspace_id,
        "entity_id": batch.entity_id,
        "created_by_user_id": batch.created_by_user_id,
        "source_draft_id": batch.source_draft_id,
        "source_kind": batch.source_kind,
        "summary": batch.summary,
        "status": batch.status,
        "task_ids": _json_safe(batch.task_ids or []),
        "details": _json_safe(batch.details or {}),
        "completed_at": _iso_loaded(batch, "completed_at"),
        "created_at": _iso_loaded(batch, "created_at"),
        "updated_at": _iso_loaded(batch, "updated_at"),
    }


def _iso_loaded(obj: Any, attr: str) -> str | None:
    value = getattr(obj, "__dict__", {}).get(attr)
    return value.isoformat() if value else None
