import DOMPurify from "dompurify";
import type { ManorDocumentRender, ManorDocumentSectionRender } from "./manorDocumentEngine";

const DOCX_EDITOR_DATA_ATTRIBUTES = [
  "data-docx-paragraph-index",
  "data-docx-source-editable",
  "data-docx-text-box-index",
  "data-docx-text-box-paragraph-index",
  "data-docx-insert-after",
  "data-docx-placeholder",
  "data-docx-alt-chunk-id",
  "data-docx-list-label",
  "data-docx-page-break",
  "data-docx-page-break-before",
  "data-docx-section-after",
  "data-docx-field",
  "data-docx-keep-next",
  "data-docx-keep-lines",
  "data-docx-widow-control",
  "data-docx-style-name",
  "data-docx-table-header",
  "data-docx-table-row-keep",
  "data-docx-floating",
  "data-docx-anchor-horizontal",
  "data-docx-anchor-vertical",
  "data-docx-anchor-page-scope",
  "data-manor-docx-layout",
  "contenteditable",
];

export interface SanitizeDocumentHtmlOptions {
  allowDocxEditorAttributes?: boolean;
  /** Only enable for HTML generated by Manor's OOXML renderer. */
  allowDocxLayoutStyles?: boolean;
}

function sanitizeSection(
  section: ManorDocumentSectionRender,
  options: SanitizeDocumentHtmlOptions,
): ManorDocumentSectionRender {
  return {
    ...section,
    headerHtml: sanitizeDocumentHtml(section.headerHtml, options),
    footerHtml: sanitizeDocumentHtml(section.footerHtml, options),
    firstHeaderHtml: sanitizeDocumentHtml(section.firstHeaderHtml, options),
    firstFooterHtml: sanitizeDocumentHtml(section.firstFooterHtml, options),
    evenHeaderHtml: sanitizeDocumentHtml(section.evenHeaderHtml, options),
    evenFooterHtml: sanitizeDocumentHtml(section.evenFooterHtml, options),
  };
}

/** Sanitize every renderer-owned body and section-furniture fragment together. */
export function sanitizeManorDocumentRender(
  rendered: ManorDocumentRender,
  options: SanitizeDocumentHtmlOptions,
): ManorDocumentRender {
  const sections = rendered.sections.map((section) => sanitizeSection(section, options));
  const first = sections[0];
  return {
    ...rendered,
    html: sanitizeDocumentHtml(rendered.html, options),
    sections,
    headerHtml: first?.headerHtml ?? sanitizeDocumentHtml(rendered.headerHtml, options),
    footerHtml: first?.footerHtml ?? sanitizeDocumentHtml(rendered.footerHtml, options),
    firstHeaderHtml: first?.firstHeaderHtml ?? sanitizeDocumentHtml(rendered.firstHeaderHtml, options),
    firstFooterHtml: first?.firstFooterHtml ?? sanitizeDocumentHtml(rendered.firstFooterHtml, options),
    evenHeaderHtml: first?.evenHeaderHtml ?? sanitizeDocumentHtml(rendered.evenHeaderHtml, options),
    evenFooterHtml: first?.evenFooterHtml ?? sanitizeDocumentHtml(rendered.evenFooterHtml, options),
  };
}

/** Sanitize HTML derived from user-controlled Office files before rendering. */
export function sanitizeDocumentHtml(
  value: string,
  options: SanitizeDocumentHtmlOptions = {},
): string {
  return DOMPurify.sanitize(value || "", {
    USE_PROFILES: { html: true },
    ALLOW_DATA_ATTR: false,
    ...(options.allowDocxEditorAttributes ? { ADD_ATTR: DOCX_EDITOR_DATA_ATTRIBUTES } : {}),
    FORBID_TAGS: [
      "base",
      "embed",
      "form",
      "iframe",
      "link",
      "meta",
      "object",
      "script",
      "style",
    ],
    FORBID_ATTR: options.allowDocxLayoutStyles ? ["srcset"] : ["style", "srcset"],
  });
}
