import DOMPurify from "dompurify";

const DOCX_EDITOR_DATA_ATTRIBUTES = [
  "data-docx-paragraph-index",
  "data-docx-source-editable",
  "data-docx-insert-after",
  "data-docx-placeholder",
  "data-docx-alt-chunk-id",
  "data-docx-list-label",
  "data-docx-page-break",
  "data-docx-page-break-before",
  "data-docx-field",
  "data-docx-keep-next",
  "data-docx-keep-lines",
  "data-docx-widow-control",
  "data-docx-style-name",
  "data-docx-table-header",
  "data-docx-table-row-keep",
  "data-manor-docx-layout",
  "contenteditable",
];

interface SanitizeDocumentHtmlOptions {
  allowDocxEditorAttributes?: boolean;
  /** Only enable for HTML generated by Manor's OOXML renderer. */
  allowDocxLayoutStyles?: boolean;
}

/** Sanitize HTML derived from user-controlled Office files before rendering. */
export function sanitizeDocumentHtml(
  value: string,
  options: SanitizeDocumentHtmlOptions = {},
): string {
  return DOMPurify.sanitize(value || "", {
    USE_PROFILES: { html: true },
    ALLOW_DATA_ATTR: false,
    ...(options.allowDocxEditorAttributes ? { ADD_ATTR: DOCX_EDITOR_DATA_ATTRIBUTES } : {}),
    FORBID_TAGS: [
      "base",
      "embed",
      "form",
      "iframe",
      "link",
      "meta",
      "object",
      "script",
      "style",
    ],
    FORBID_ATTR: options.allowDocxLayoutStyles ? ["srcset"] : ["style", "srcset"],
  });
}
